force-app/main/default/objects/MailMatchingDetail__c.object
<CustomObject>
    <fields>
        <fullName>EndText1__c</fullName>
        <label>終了テキスト1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FieldApi__c</fullName>
        <label>フィールドAPI名</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ManualMatching__c</fullName>
        <label>正規表現マッチング</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SettingMaster__c</fullName>
        <label>メール取込設定</label>
        <referenceTo>MailMatchingSetting__c</referenceTo>
        <relationshipName>MailMatchingDetails</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>StartText1__c</fullName>
        <label>開始テキスト1</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StartText2__c</fullName>
        <label>開始テキスト2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Mail2Xマッチング設定</label>
    <nameField>
        <label>Mail2Xマッチング設定名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MailMatchingSetting__c.object
<CustomObject>
    <fields>
        <fullName>AddressKey__c</fullName>
        <label>受信対象メールアドレス</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>AddressTarget__c</fullName>
        <label>参照対象アドレス</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>From</fullName>
                    <default>true</default>
                    <label>From:アドレス</label>
                </value>
                <value>
                    <fullName>To</fullName>
                    <label>To:アドレス</label>
                </value>
                <value>
                    <fullName>Transfer</fullName>
                    <label>最終転送アドレス</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>AttachmentFile__c</fullName>
        <defaultValue>false</defaultValue>
        <label>添付ファイルの取込</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Availability__c</fullName>
        <defaultValue>false</defaultValue>
        <label>有効</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ObjectApi__c</fullName>
        <label>対象オブジェクト</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OriginalMessageApi__c</fullName>
        <label>オリジナルメッセージ</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProviderMailAddressApi__c</fullName>
        <label>送信元メールアドレス</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProviderNameApi__c</fullName>
        <label>送信者</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SaveErrorLog__c</fullName>
        <defaultValue>false</defaultValue>
        <label>エラーをレコードに保存する</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SettingNameApi__c</fullName>
        <label>Mail2X設定</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubjectApi__c</fullName>
        <label>件名</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Mail2X設定</label>
    <nameField>
        <label>Mail2X設定名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/MailMatchingHandlerTest.cls
@isTest
private class MailMatchingHandlerTest {
  static final String subject = 'Dummy';
  static final String senderName = 'Mail2x Taro';
  static final String emailAddress = 'dummy@dummy.com';
  static final String toAddress = 'dummy2@dummy.com';

  @isTest
  private static void sendMailTestNavText() {
    String plainTextBody = 'dummy test sample\ntext\ntext';
    Messaging.InboundEmail email = new Messaging.InboundEmail();
    Messaging.InboundEnvelope env = new Messaging.InboundEnvelope();
    Messaging.InboundEmail.Header headerItem = new Messaging.InboundEmail.Header();
    headerItem.name = 'received';
    headerItem.value = 'SEND STRAT for <' + emailAddress + '> END';
    List<Messaging.InboundEmail.Header> headers = new List<Messaging.InboundEmail.Header>{ headerItem };

    email.plainTextBody = plainTextBody;
    email.fromAddress = emailAddress;
    email.fromName = senderName;
    email.toAddresses = new List<String>{ toAddress };
    email.ccAddresses = new List<String>{};
    email.headers = headers;
    email.subject = subject;

    MailMatchingHandler mmh = new MailMatchingHandler();

    Test.startTest();
    MailMatchingSetting__c mailMatchingSetting = new MailMatchingSetting__c(
      Name = 'TestMail',
      OriginalMessageApi__c = 'mail2x__OriginalMessage__c',
      SubjectApi__c = 'mail2x__Subject__c',
      AddressKey__c = 'dummy@dummy.com',
      ObjectApi__c = 'mail2x__InquiryMail__c',
      AddressTarget__c = 'From',
      Availability__c = true,
      AttachmentFile__c = true,
      SettingNameApi__c = 'mail2x__SettingNameApi__c',
      ProviderNameApi__c = 'mail2x__ProviderName__c',
      ProviderMailAddressApi__c = 'mail2x__ProviderMailAddress__c'
    );
    insert mailMatchingSetting;

    MailMatchingDetail__c mailMatchingDetail = new MailMatchingDetail__c(
      Name = 'mailMatchingDetail',
      FieldApi__c = 'mail2x__detail__c',
      SettingMaster__c = mailMatchingSetting.Id,
      ManualMatching__c = '',
      StartText1__c = 'dummy',
      StartText2__c = 'sample',
      EndText1__c = 'text'
    );
    insert mailMatchingDetail;

    Messaging.InboundEmailResult result = mmh.handleInboundEmail(email, env);
    Test.stopTest();
  }

  @isTest
  private static void sendMailTestNavDateTime() {
    String plainTextBody = 'dummy test sample\n2020年12月12日12時12分\nText\n';

    Messaging.InboundEmail email = new Messaging.InboundEmail();
    Messaging.InboundEnvelope env = new Messaging.InboundEnvelope();
    Messaging.InboundEmail.Header headerItem = new Messaging.InboundEmail.Header();
    headerItem.name = 'received';
    headerItem.value = 'SEND STRAT for <' + emailAddress + '> END';
    List<Messaging.InboundEmail.Header> headers = new List<Messaging.InboundEmail.Header>{ headerItem };

    email.plainTextBody = plainTextBody;
    email.fromAddress = emailAddress;
    email.fromName = senderName;
    email.toAddresses = new List<String>{ toAddress };
    email.ccAddresses = new List<String>{};
    email.headers = headers;
    email.subject = subject;

    MailMatchingHandler mmh = new MailMatchingHandler();

    Test.startTest();
    MailMatchingSetting__c mailMatchingSetting = new MailMatchingSetting__c(
      Name = 'TestMail',
      OriginalMessageApi__c = 'mail2x__OriginalMessage__c',
      SubjectApi__c = 'mail2x__Subject__c',
      AddressKey__c = 'dummy2@dummy.com',
      ObjectApi__c = 'mail2x__InquiryMail__c',
      AddressTarget__c = 'To',
      Availability__c = true,
      AttachmentFile__c = true,
      SettingNameApi__c = 'mail2x__SettingNameApi__c',
      ProviderNameApi__c = 'mail2x__ProviderName__c',
      ProviderMailAddressApi__c = 'mail2x__ProviderMailAddress__c'
    );
    insert mailMatchingSetting;

    MailMatchingDetail__c mailMatchingDetail = new MailMatchingDetail__c(
      Name = 'mailMatchingDetail',
      FieldApi__c = 'mail2x__InquiryDateTime__c',
      SettingMaster__c = mailMatchingSetting.Id,
      ManualMatching__c = '',
      StartText1__c = 'dummy test sample',
      StartText2__c = '',
      EndText1__c = '\n'
    );
    insert mailMatchingDetail;

    Messaging.InboundEmailResult result = mmh.handleInboundEmail(email, env);
    Test.stopTest();
  }

  @isTest
  private static void sendMailTestNavWithAttachment() {
    String plainTextBody = 'dummy test sample\ntext\ntext';

    Messaging.InboundEmail email = new Messaging.InboundEmail();
    Messaging.InboundEnvelope env = new Messaging.InboundEnvelope();
    Messaging.InboundEmail.Header headerItem = new Messaging.InboundEmail.Header();
    headerItem.name = 'received';
    headerItem.value = 'SEND STRAT for <' + emailAddress + '> END';
    List<Messaging.InboundEmail.Header> headers = new List<Messaging.InboundEmail.Header>{ headerItem };

    email.plainTextBody = plainTextBody;
    email.fromAddress = emailAddress;
    email.fromName = senderName;
    email.toAddresses = new List<String>{ toAddress };
    email.ccAddresses = new List<String>{};
    email.headers = headers;
    email.subject = subject;

    MailMatchingHandler mmh = new MailMatchingHandler();

    Messaging.InboundEmail.BinaryAttachment attachment = new Messaging.InboundEmail.BinaryAttachment();
    attachment.body = blob.valueOf('attachment text');
    attachment.fileName = 'textfileone.txt';
    attachment.mimeTypeSubType = 'text/plain';
    email.binaryAttachments = new List<Messaging.inboundEmail.BinaryAttachment>{ attachment };

    Test.startTest();
    MailMatchingSetting__c mailMatchingSetting = new MailMatchingSetting__c(
      Name = 'TestMail',
      OriginalMessageApi__c = 'mail2x__OriginalMessage__c',
      SubjectApi__c = 'mail2x__Subject__c',
      AddressKey__c = 'dummy@dummy.com',
      ObjectApi__c = 'mail2x__InquiryMail__c',
      AddressTarget__c = 'From',
      Availability__c = true,
      AttachmentFile__c = true,
      SettingNameApi__c = 'mail2x__SettingNameApi__c',
      ProviderNameApi__c = 'mail2x__ProviderName__c',
      ProviderMailAddressApi__c = 'mail2x__ProviderMailAddress__c'
    );
    insert mailMatchingSetting;

    MailMatchingDetail__c mailMatchingDetail = new MailMatchingDetail__c(
      Name = 'mailMatchingDetail',
      FieldApi__c = 'mail2x__detail__c',
      SettingMaster__c = mailMatchingSetting.Id,
      ManualMatching__c = '',
      StartText1__c = 'dummy',
      StartText2__c = 'sample',
      EndText1__c = ''
    );
    insert mailMatchingDetail;

    Messaging.InboundEmailResult result = mmh.handleInboundEmail(email, env);
    Test.stopTest();
  }

  @isTest
  private static void sendMailTestManual() {
    String plainTextBody = 'dummy test sample\ntext\ntext';

    Messaging.InboundEmail email = new Messaging.InboundEmail();
    Messaging.InboundEnvelope env = new Messaging.InboundEnvelope();
    Messaging.InboundEmail.Header headerItem = new Messaging.InboundEmail.Header();
    headerItem.name = 'received';
    headerItem.value = 'SEND STRAT for <' + emailAddress + '> END';
    List<Messaging.InboundEmail.Header> headers = new List<Messaging.InboundEmail.Header>{ headerItem };

    email.plainTextBody = plainTextBody;
    email.fromAddress = emailAddress;
    email.fromName = senderName;
    email.toAddresses = new List<String>{ toAddress };
    email.ccAddresses = new List<String>{};
    email.headers = headers;
    email.subject = subject;

    MailMatchingHandler mmh = new MailMatchingHandler();

    Test.startTest();
    MailMatchingSetting__c mailMatchingSetting = new MailMatchingSetting__c(
      Name = 'TestMail',
      OriginalMessageApi__c = 'mail2x__OriginalMessage__c',
      SubjectApi__c = 'mail2x__Subject__c',
      AddressKey__c = 'dummy@dummy.com',
      ObjectApi__c = 'mail2x__InquiryMail__c',
      AddressTarget__c = 'transfer',
      Availability__c = true,
      AttachmentFile__c = true,
      SettingNameApi__c = 'mail2x__SettingNameApi__c',
      ProviderNameApi__c = 'mail2x__ProviderName__c',
      ProviderMailAddressApi__c = 'mail2x__ProviderMailAddress__c'
    );
    insert mailMatchingSetting;

    MailMatchingDetail__c mailMatchingDetail = new MailMatchingDetail__c(
      Name = 'mailMatchingDetail',
      FieldApi__c = 'mail2x__detail__c',
      SettingMaster__c = mailMatchingSetting.Id,
      ManualMatching__c = 'dummy.*?\n(.*?)\n',
      StartText1__c = 'dummy',
      StartText2__c = '',
      EndText1__c = ''
    );
    insert mailMatchingDetail;

    Messaging.InboundEmailResult result = mmh.handleInboundEmail(email, env);
    Test.stopTest();
  }

  @isTest
  private static void sendMailTestNavExceptioon() {
    String plainTextBody = 'dummy test sample';

    Messaging.InboundEmail email = new Messaging.InboundEmail();
    Messaging.InboundEnvelope env = new Messaging.InboundEnvelope();
    Messaging.InboundEmail.Header headerItem = new Messaging.InboundEmail.Header();
    headerItem.name = 'received';
    headerItem.value = 'SEND STRAT for <' + emailAddress + '> END';
    List<Messaging.InboundEmail.Header> headers = new List<Messaging.InboundEmail.Header>{ headerItem };

    email.plainTextBody = plainTextBody;
    email.fromAddress = emailAddress;
    email.fromName = senderName;
    email.toAddresses = new List<String>{ toAddress };
    email.ccAddresses = new List<String>{};
    email.headers = headers;
    email.subject = subject;

    MailMatchingHandler mmh = new MailMatchingHandler();

    Test.startTest();
    MailMatchingSetting__c mailMatchingSetting = new MailMatchingSetting__c(
      Name = 'TestMail',
      OriginalMessageApi__c = 'mail2x__OriginalMessage__c',
      SubjectApi__c = 'mail2x__Subject__c',
      AddressKey__c = 'dummy@dummy.com',
      ObjectApi__c = 'mail2x__InquiryMail__c',
      AddressTarget__c = 'From',
      Availability__c = true,
      AttachmentFile__c = true,
      SettingNameApi__c = 'mail2x__SettingNameApi__c',
      ProviderNameApi__c = 'mail2x__ProviderName__c',
      ProviderMailAddressApi__c = 'mail2x__ProviderMailAddress__c',
      SaveErrorLog__c = true
    );
    insert mailMatchingSetting;

    MailMatchingDetail__c mailMatchingDetail = new MailMatchingDetail__c(
      Name = 'mailMatchingDetail',
      FieldApi__c = 'mail2x__dummy__c',
      SettingMaster__c = mailMatchingSetting.Id,
      ManualMatching__c = '',
      StartText1__c = 'dummy test sample',
      StartText2__c = '',
      EndText1__c = '\n'
    );
    insert mailMatchingDetail;

    Messaging.InboundEmailResult result = mmh.handleInboundEmail(email, env);
    Test.stopTest();
  }
}