force-app/main/default/objects/Mail2XErrorMail__c.object
<CustomObject>
    <fields>
        <fullName>From__c</fullName>
        <label>From</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>HtmlBody__c</fullName>
        <label>HtmlBody</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TextBody__c</fullName>
        <label>TextBody</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>To__c</fullName>
        <label>To</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Mail2Xエラーメール</label>
    <nameField>
        <label>Mail2Xエラーメール名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/MailThrowErrorLog.cls
global class MailThrowErrorLog implements Messaging.InboundEmailHandler {
    public with sharing class HandleException extends Exception {}

    global Messaging.InboundEmailResult handleInboundEmail(Messaging.InboundEmail email, Messaging.InboundEnvelope envelope) {
        Messaging.InboundEmailResult result = new Messaging.InboundEmailresult();

        if (
            Schema.sObjectType.Mail2XErrorMail__c.isCreateable() != true ||
            Schema.sObjectType.Mail2XErrorMail__c.fields.Name.isCreateable() != true ||
            Schema.sObjectType.Mail2XErrorMail__c.fields.From__c.isCreateable() != true ||
            Schema.sObjectType.Mail2XErrorMail__c.fields.To__c.isCreateable() != true ||
            Schema.sObjectType.Mail2XErrorMail__c.fields.Name__c.isCreateable() != true ||
            Schema.sObjectType.Mail2XErrorMail__c.fields.Subject__c.isCreateable() != true ||
            Schema.sObjectType.Mail2XErrorMail__c.fields.TextBody__c.isCreateable() != true ||
            Schema.sObjectType.Mail2XErrorMail__c.fields.HtmlBody__c.isCreateable() != true
        ) {
            return result;
        }

        String subject = email.subject;
        String originalBody = email.plainTextBody;
        String originalHtmlBody = email.htmlBody;
        String eaddr = email.fromAddress;
        String ename = email.fromName;
        List<String> toaddr = email.toAddresses;

        result.message = originalBody;
        result.message += '\n';
        result.success = true;

        Mail2XErrorMail__c errorObject = new Mail2XErrorMail__c(
            Name = 'MailThrowErrorLog',
            From__c = eaddr,
            To__c = String.join(toaddr, ',\n'),
            Name__c = ename,
            Subject__c = subject,
            TextBody__c = originalBody,
            HtmlBody__c = originalHtmlBody
        );

        insert errorObject;
        return result;
    }
}